#!/bin/bash

OUT=""

VELO_STAT=$(ip addr show wg-home 2>&1 | grep "inet ")
if [ $(wc -c <<< $VELO_STAT) -gt "5" ]; then
    OUT+=""
    OUT+=" H:$(echo $VELO_STAT | awk ' {print $2} ')"
else
    OUT+=" H:OFF"
fi

#echo $VELO_STAT | awk ' {print $2} '
echo $OUT
