

$powermenu = (S)hutdown Sl(E)ep (H)ibernate (R)eboot (L)ogout (C)ancel

bind = $mainMod SHIFT, X, submap, $powermenu

submap = $powermenu

binde = $mainMod SHIFT, S, exec, shutdown now
binde = $mainMod SHIFT, R, exec, reboot
binde = $mainMod SHIFT, L, exec, hyprctl dispatch exit
binde = $mainMod SHIFT, E, exec, systemctl suspend
binde = $mainMod SHIFT, H, exec, systemctl hibernate
binde = $mainMod SHIFT, C, submap, reset

bind = , escape, submap, reset
bind = $mainMod SHIFT, X, submap, reset

submap = reset

bind  = $mainMod, X, exec, hyprlock
