local Plug = vim.fn["plug#"]

vim.call("plug#begin", "~/.vim/plugged/")

-- UI
Plug("luisiacc/gruvbox-baby")
Plug("kyazdani42/nvim-web-devicons")
Plug("kyazdani42/nvim-tree.lua")
Plug("nvim-lualine/lualine.nvim")
Plug("akinsho/bufferline.nvim",  {tag='v2.*'})
Plug("PeterRincker/vim-searchlight")
Plug("lukas-reineke/indent-blankline.nvim")
Plug("nvim-lua/plenary.nvim")
Plug("ThePrimeagen/harpoon")
Plug("nvim-telescope/telescope.nvim")
Plug("ThePrimeagen/git-worktree.nvim")
-- LSP SELECT
Plug("neoclide/coc.nvim", { branch = 'release'})
-- Plug("hrsh7th/nvim-cmp")
-- LSP SELECT
Plug("honza/vim-snippets")
Plug("phaazon/hop.nvim")
Plug("unblevable/quick-scope")
Plug("christoomey/vim-tmux-navigator")
Plug("tpope/vim-surround")
Plug("TimUntersberger/neogit")
Plug("sindrets/diffview.nvim")
Plug("airblade/vim-gitgutter")
Plug("nvim-treesitter/nvim-treesitter",  {['do'] = ':TSUpdate'})
Plug("nvim-treesitter/nvim-treesitter-textobjects")
Plug("tpope/vim-commentary")
Plug("tpope/vim-repeat")
Plug("puremourning/vimspector")
Plug("junegunn/fzf", { ['do'] = vim.fn['fzf#install']})
Plug("junegunn/fzf.vim")
Plug("stevearc/aerial.nvim")
Plug("jiangmiao/auto-pairs")
Plug("folke/which-key.nvim")
Plug("JoosepAlviste/nvim-ts-context-commentstring")
-- Plug("preservim/nerdcommenter")
Plug("terrortylor/nvim-comment")
Plug("jvirtanen/vim-hcl")
Plug("leafOfTree/vim-vue-plugin")

-- COPILOT PILOT
Plug("github/copilot.vim")
-- Plug("zbirenbaum/copilot.lua")
-- COPILOT END

vim.call("plug#end")

require("options")
require("keyMappings")
require("autocmds")
require("textObjects")
require("plug-config/lualine")
require("plug-config/gruvbox-baby")
require("plug-config/nvimTree")
require("plug-config/lualine")
require("plug-config/bufferline")
require("plug-config/treeSitter")
require("plug-config/comment")
require("plug-config/neogit")
require("plug-config/diffview")
require("plug-config/gitGutter")
require("plug-config/aerial")
require("plug-config/hop")
require("plug-config/fzf")
require("plug-config/vimspector")
require("plug-config/quickScope")
require("plug-config/whichKey")
-- LSP SELECT
require("plug-config/coc")
-- require("plug-config/cmp")
-- LSP SELECT
require("plug-config/ctrlp")
require("plug-config/harpoon")
require("plug-config/telescope")
require("plug-config/vue-plugin")
require("plug-config/Copilot")
