#!/usr/bin/env bash
nitrogen --restore
xset r rate 300 50
setxkbmap -option caps:super
killall xcape 2>/dev/null; xcape -e 'Super_L=Escape'
xmodmap -e "keycode 105 = asciitilde"
$HOME/.config/polybar/launch.sh
